---
layout: post
---

I’ve been slacking on updating the blog, mostly because I’ve been trying to focus on my diss and a few other projects I’ve been working on. I at least had time to write this piece, a sketch for the theoretical section that will eventually appear in my diss introduction. That will be in some heavily modified form, anyway. I’ll have to tweak it to make it a workable intro, since here I don’t talk about punk or anything else musical, really. I’d also like to expand it into a more general methodological essay down the road, which will require reorganizing, adding examples from outside of punk, etc.. I’ve attached a .pdf version of the text with footnotes and a bibliography in case you want to fact-check my work (encoding it for the blog is way beyond my ability right now).

My dissertation is about 1970s New York punk (the Ramones, Patti Smith Group, Blondie, etc.). It takes its cue from what I see as the *aporetic* status of punk in the popular and scholarly world: On the one hand, punk is seemingly self-evident as a genre, three-chord rock that sonifies urban grit and grime. On the other hand, it is a genre that is curiously diffuse from a stylistic and philosophical standpoint, and has inspired a great deal of conflicting accounts of what it is all about. It’s hard for any given narrative about punk – as anarchic noise, as retro rock, as deconstructive postmodern avant-garde, etc. – to gather up the Sex Pistols, Blondie, Patti Smith, and Suicide (let alone explain how those earlier artists link up to later groups like Bad Brains, Green Day, and Pussy Riot).

This question pointed me toward genre theory. In attempting to unravel punk’s puzzling status, I started thinking more about what genres are, how they work musically and conceptually, and where their identity really lies (In sound? In style? In people’s imaginations?). I started to link this up to my more general interest in historical materialist philosophy (which I explain a bit more about below). It occurred to me that some of genre’s more evasive aspects start to look a little more clear when linked up to the tensions between ideas and social practices that have been placed at the fore in a lot of philosophical projects from German idealism to Marxism to critical theory. Essentially, my starting place was attempting to think about how genres exist in a fuzzy space between a.) ideas, the strictly imagined and invented kind of thinking about genre that stresses its ideological rather than physical characteristics, and b.) musical material, which often, especially in talk about punk, gets reduced to mere sonic or musical similarity (eg. I-IV-V progressions, feedback, etc.). This is a first attempt at articulating an account of what that space is. Here it is.
<br>
**Genre & Historical Materialism**
<br>
At the core of my account is the idea of historical materialism. Simply put by the philosopher Raya Dunayevskaya, historical materialism hinges on “the unity of theory and practice.”  The central question guiding this line of inquiry concerns the troubled relationship between a.) the domain of material life, including not just production/reproduction of human life but more broadly, the patterns and activities humans engage in socially, and b.) the domain of thought, the intellectual activities through which human beings exchange with each other and make sense of their world. Historical materialism names not only the set of concepts and ways of thinking about this, but also a tradition concerned with this problematic. This links a range of philosophical and political projects, most centrally in three key moments: 1.) German philosophy of the late eighteenth- and early nineteenth-centuries, especially the idealism of Kant and Hegel 2.) Marxian thought proper and its many instantiations in political theory (Leninism, Maoism, etc.), and 3.) the many traditions that engage with Marx during the twentieth-and twenty-first-centuries: the Frankfurt School, Black Radical thought, Marxist-feminism, and so on. 

Historical materialism regards the linking of thought and activity as a necessary one, but also a problematic one. It is easy to argue that we *should* take seriously both intellectual and political activity (as I would), but it’s important to remember that people usually don’t. Take for example, the relationship between academic musicology and social movements. While we’d all love to believe our discipline can contribute to real-world change, I’m sure I’m not alone in recognizing that, minimally, it doesn’t always do so. The philosopher Gillian Rose argues that historical materialism be thought of *aporetically*, “as stressing the gap between theory and practice, which strain towards each other.”  It thus names the fraught effort to unite the two spheres, to bend thought toward activity and live in a way that is more in accordance with our notions of the good.

This is why music has a special place in discussions of historical materialism. Like human sociality more generally, music exists in a blurry space between its material constitution and its entanglement in ideas, that complex collection of values, categories, and concepts that we use to engage with music. Music is, on the one hand, an object. It is sensuous *thing*, what we call sound. On the other hand, music is an *idea*. The term music functions as a placeholder, one which often far exceeds the thing it stands in for. Music is about meaning, feelings, culture at large. Sometimes, it feels like it is about anything but music. This gives it a dual identity. It is an idea grafted onto sound. And this graft rarely takes. Music is unstable because these two identities make competing claims, ones that are seldom reconciled. I would allege (contentiously and in a way that can’t possibly be defended in this dissertation), that the history of music studies has largely been a series of figures on this untenable relationship.

Genre plays a special role in this conversation, because it sits at the intersection of music as cultural practice and music as sound. Let me formalize a bit more clearly what I mean when I refer to genre before I expand on that. In the loosest sense, genre refers to the material and conceptual elements that link texts of various kinds, what I’ll refer to hereafter as “norms.”  As the genre theorist John Frow writes, genre in its most general refers to “a set of conventional and highly organized constraints on the production and interpretation of meaning.”  In other words, genre refers to the categories that musicians and audiences use to negotiate musical practices. Such practices not only include key categories for musical works, novels, and films (areas where the term most often appears), but also non-artistic practices (official discourse like emails and announcements, even everyday speech acts, and many other examples). Categories saturate our lives; as Jason Toynbee suggests, few things escape the “inevitability of genre.” 

	This is not necessarily because rules abound in some mythically ordered universe, but because we depend on relationships between texts in order to find them meaningful. Indeed, constraints should not only suggest restrictions (a partial reason for my preference of the term norms, about which I’ll say more below). Really, as David Brackett writes, genre enables meaning:
>It is a condition of the legibility of a text that a listener can place it in the context of a >genre, that is, in the context of how sounds, lyrics, images, performer personae, >musical rhetoric, and a generic label (among other things) can be related. In order for >this to occur, texts must cite or refer to generic conventions that predate them. 
